### ISSUE TITLE
Why is --patches not the default?

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/sbb_binarization#45]
The README says:
> Note In virtually all cases, applying the --patches flag will improve the quality of results.

Why is it not the default? Why no `--no-patches` option instead?

**Comment by mikegerber** [comment]
FWIW, in the OCR-D CLI, `use_patches=True` is the default and there does not even seem to be an option to turn it off: https://github.com/qurator-spk/sbb_binarization/blob/master/sbb_binarize/ocrd_cli.py#L109

**Comment by cneud** [comment]
Full story: https://github.com/qurator-spk/sbb_binarization/pull/5/commits/eece89b9acd40808d98da98093a942518ff4dc5c

TL;DR > [...this parameter should be set "True", otherwise model will see image at once and the quality will be terrible](https://github.com/qurator-spk/sbb_binarization/pull/5/commits/eece89b9acd40808d98da98093a942518ff4dc5c#r506200961)

My vote goes towards always [using patches](https://github.com/qurator-spk/sbb_binarization/blob/master/sbb_binarize/sbb_binarize.py#L105) and completely getting rid of the CLI option.
